### ISSUE TITLE
Allow downloading bytehound from the internet

### ISSUE THREAD

**Issue by PierreBesson** [paritytech/ansible-galaxy#17]
Currently bytehound seems to be manually installed on machines. It would be good to add support for downloading the `libbytehound.so` from a specific URL.

**Comment by gabreal** [comment]
doesn't the node role already support this e.g. https://github.com/paritytech/ansible-galaxy/blob/main/roles/node/defaults/main.yml#L229 ?

**Comment by PierreBesson** [comment]
Yes I confirm that it is actually supported. We just need better docs on what options are available.
