### ISSUE TITLE
changed CLI parameters

### ISSUE THREAD

**Issue by ilhanu** [paritytech/ansible-galaxy#37]
With Polkadot release [v0.9.43](https://github.com/paritytech/polkadot/releases/tag/v0.9.43) there were changing CLI flags. This breaks the current deployment with the ansible-galaxy and leads to a non-working version. 

```
--rpc-max-payload (replaced by --rpc-max-request-size and --rpc-max-response-size)
--ws-max-out-buffer-capacity
--ws-external (replaced by --rpc-external)
--unsafe-ws-external (replaced by --unsafe-rpc-external)
--ipc--path
--ws-port (replaced by --rpc-port)
--ws-max-connections (replaced by --rpc-max-connections)
--rpc-http (replaced by --rpc-addr)
--rpc-ws (replaced by --rpc-addr)
```

**Comment by BulatSaif** [comment]
This was already fixed in https://github.com/paritytech/ansible-galaxy/pull/31
for version  `v0.9.42` and lower you should set `node_legacy_rpc_flags: true` (default )
for version `v0.9.43` and higher you set `node_legacy_rpc_flags: false`
